######################################################################
# Automatically generated by qmake (3.0) lun. avr. 11 15:55:40 2016
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = Qt
INCLUDEPATH += .

# Input
SOURCES += main_test.cpp
